name: Build and push images
on:
  workflow_dispatch:
    inputs:
      image:
        description: 'Select name of image to build'
        required: true
        default: ''
        type: choice
        options:
          - dataset-operator
          - csi-s3

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}-${{ inputs.image }}
  BUILD_DIR: ''

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels)
        id: meta-data
        uses: docker/metadata-action@v3
        with:
          images: '${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}'
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=branch,suffix=-build-${{ github.run_id }}
            type=ref,event=tag
            type=ref,event=pr
            type=raw,value=build-${{ github.run_id }}

      - name: Build and push Dataset Operator
        if: inputs.image == 'dataset-operator'
        uses: docker/build-push-action@v3
        with:
          context: 'src/dataset-operator'
          push: true
          tags: ${{ steps.meta-data.outputs.tags }}
          labels: ${{ steps.meta-data.outputs.labels }}

      - name: Build and push csi-s3
        if: inputs.image == 'csi-s3'
        uses: docker/build-push-action@v3
        with:
          context: 'src/csi-s3'
          push: true
          file: 'src/csi-s3/cmd/s3driver/Dockerfile.full'
          tags: ${{ steps.meta-data.outputs.tags }}
          labels: ${{ steps.meta-data.outputs.labels }}
